railway_booking_system/railway_booking_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('train_search_service/', include('train_search_service.urls')),
    path('seat_booking_service/', include('seat_booking_service.urls')),
    path('train_schedule_service/', include('train_schedule_service.urls')),
    path('external_api_service/', include('external_api_service.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='user_management/login.html'), name='login'),
    path('', include('user_management.urls'))

]

railway_booking_system/train_schedule_service/urls.py
from django.urls import path,include
from .views import DashboardView, EditTrainView, DeleteTrainView, AddTrainView, ScheduleTrainView, EditScheduleView, DeleteScheduleView

urlpatterns = [
    path('add_train/', AddTrainView.as_view(), name='add_train'),
    path('schedule_train/', ScheduleTrainView.as_view(), name='schedule_train'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('edit_train/<int:train_id>/', EditTrainView.as_view(), name='edit_train'),
    path('delete_train/<int:train_id>/', DeleteTrainView.as_view(), name='delete_train'),
    path('edit_schedule/<int:schedule_id>/', EditScheduleView.as_view(), name='edit_schedule'),
    path('delete_schedule/<int:schedule_id>/', DeleteScheduleView.as_view(), name='delete_schedule'),
]

railway_booking_system/user_management/urls.py
from django.urls import path
from .views import IndexView, UserSignupView, UserLoginView, UserLogoutView

urlpatterns = [
    path('', IndexView.as_view(), name='home'),
    path('signup/', UserSignupView.as_view(), name='signup'),
    path('login/', UserLoginView.as_view(), name='login'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
]

railway_booking_system/train_schedule_service/models.py
from django.db import models
from datetime import date 

class Train(models.Model):
    train_name = models.CharField(max_length=100, default='')
    route = models.CharField(max_length=50, default='')

    def __str__(self):
        return self.train_name

class TrainSchedule(models.Model):
    train = models.ForeignKey(Train, on_delete=models.CASCADE)
    schedule_date = models.DateField(default=date.today)
    departure_time = models.CharField(max_length=100, default='')
    start_location = models.CharField(max_length=50, default='')
    destination = models.CharField(max_length=50, default='')

    def __str__(self):
        return f"{self.train.train_name} - {self.schedule_date}"

railway_booking_system/train_schedule_service/forms.py
# forms.py

from django import forms
from .models import Train, TrainSchedule

class TrainForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TrainForm, self).__init__(*args, **kwargs)
        first_way = [("COLOMBO - JAFFNA", "COLOMBO - JAFFNA"),
                     ("COLOMBO - GALLE", "COLOMBO - GALLE"),
                     ("COLOMBO - BADULLA", "COLOMBO - BADULLA"),
                     ("COLOMBO - TRINCOMALE", "COLOMBO - TRINCOMALE")]
        self.fields['route'].widget = forms.Select(choices=first_way)

    class Meta:
        model = Train
        fields = ['train_name', 'route']

class TrainScheduleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(TrainScheduleForm, self).__init__(*args, **kwargs)
        locations = [("COLOMBO", "COLOMBO"),
                     ("JAFFNA", "JAFFNA"),
                     ("GALLE", "GALLE"),
                     ("BADULLA", "BADULLA"),
                     ("TRINCOMALE", "TRINCOMALE")]
        self.fields['start_location'].widget = forms.Select(choices=locations)
        self.fields['destination'].widget = forms.Select(choices=locations)

        departure_times = [('{}:00'.format(hour), '{}:00'.format(hour)) for hour in range(8, 24)] + [('00:00', '00:00')]
        self.fields['departure_time'].widget = forms.Select(choices=departure_times)

    class Meta:
        model = TrainSchedule
        fields = ['train', 'schedule_date', 'departure_time','start_location', 'destination']


railway_booking_system/train_schedule_service/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from django.contrib import messages
from django.views import View
from .forms import TrainForm, TrainScheduleForm
from .models import Train, TrainSchedule
from django.utils.decorators import method_decorator


class DashboardView(View):
    def get(self, request):
        trains = Train.objects.all()
        schedules = TrainSchedule.objects.all()
        return render(request, 'train_schedule_service/dashboard.html', {'trains': trains, 'schedules': schedules})

class EditTrainView(View):
    def get(self, request, train_id):
        train = get_object_or_404(Train, pk=train_id)
        form = TrainForm(instance=train)
        return render(request, 'train_schedule_service/train_add_form.html', {'form': form})

    def post(self, request, train_id):
        train = get_object_or_404(Train, pk=train_id)
        form = TrainForm(request.POST, instance=train)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
        return render(request, 'train_schedule_service/train_add_form.html', {'form': form})

class DeleteTrainView(View):
    def post(self, request, train_id):
        train = get_object_or_404(Train, pk=train_id)
        train.delete()
        return redirect('dashboard')

class AddTrainView(View):
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def get(self, request):
        form = TrainForm()
        return render(request, 'train_schedule_service/train_add_form.html', {'form': form})

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def post(self, request):
        form = TrainForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Train successfully added!')
            return redirect('dashboard')
        return render(request, 'train_schedule_service/train_add_form.html', {'form': form})

class ScheduleTrainView(View):
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def get(self, request):
        form = TrainScheduleForm()
        return render(request, 'train_schedule_service/schedule_form.html', {'form': form})

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def post(self, request):
        form = TrainScheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('dashboard')
        return render(request, 'train_schedule_service/schedule_form.html', {'form': form})

class EditScheduleView(View):
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def get(self, request, schedule_id):
        schedule = get_object_or_404(TrainSchedule, pk=schedule_id)
        form = TrainScheduleForm(instance=schedule)
        return render(request, 'train_schedule_service/schedule_form.html', {'form': form})

    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def post(self, request, schedule_id):
        schedule = get_object_or_404(TrainSchedule, pk=schedule_id)
        form = TrainScheduleForm(request.POST, instance=schedule)
        if form.is_valid():
            form.save()
            messages.success(request, 'Schedule successfully updated!')
            return redirect('dashboard')
        return render(request, 'train_schedule_service/schedule_form.html', {'form': form})

class DeleteScheduleView(View):
    @method_decorator(user_passes_test(lambda u: u.is_superuser))
    def post(self, request, schedule_id):
        schedule = get_object_or_404(TrainSchedule, pk=schedule_id)
        schedule.delete()
        messages.success(request, 'Schedule successfully deleted!')
        return redirect('dashboard')

railway_booking_system/templates/train_schedule_service/dashboard.html
{% extends 'main/base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>
    <style>
    </style>
</head>

<body>
    <div class="container">
        <h1 class="mt-5">Dashboard</h1>
        <ul class="nav nav-tabs mt-4">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'add_train' %}">Add Train</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'schedule_train' %}">Schedule Train</a>
            </li>
        </ul>
        <div class="card">
            <h2 class="mt-5">Trains</h2>
            <table class="table mt-4">
                <thead>
                    <tr>
                        <th>Train Name</th>
                        <th>Train Route</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for train in trains %}
                    <tr>
                        <td>{{ train.train_name }}</td>
                        <td>{{ train.route }}</td>
                        <td>
                            <!-- Add CRUD operation links/buttons for trains here -->
                            <a href="{% url 'edit_train' train.pk %}" class="btn btn-primary btn-sm">Edit</a>
                            <a href="{% url 'delete_train' train.pk %}" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
<br><Br><br>
        <div class="card">
            <!-- For Schedules Table -->
            <h2 class="mt-5">Schedules</h2>
            <table class="table mt-4">
                <thead>
                    <tr>
                        <th>Train</th>
                        <th>Schedule Date</th>
                        <th>Departure Time</th>
                        <th>Start Location</th>
                        <th>Destination</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for schedule in schedules %}
                    <tr>
                        <td>{{ schedule.train }}</td>
                        <td>{{ schedule.schedule_date }}</td>
                        <td>{{ schedule.departure_time }}</td>
                        <td>{{ schedule.start_location }}</td>
                        <td>{{ schedule.destination }}</td>
                        <td>
                            <!-- Add CRUD operation links/buttons for schedules here -->
                            <a href="{% url 'edit_schedule' schedule.pk %}" class="btn btn-primary btn-sm">Edit</a>
                            <a href="{% url 'delete_schedule' schedule.pk %}" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

    </div>

    <!-- Bootstrap JavaScript (optional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>
{% endblock %}

railway_booking_system/templates/train_schedule_service/schedule_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmation Deletion</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Confirm Deletion</h2>
                <p>Are you sure you want to delete {{ schedule.train }}, {{ schedule.start_location }} to {{ schedule.destination }}?</p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

railway_booking_system/templates/train_schedule_service/schedule_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Schedule Train</title>
    <!-- Bootstrap CSS link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Font Awesome CSS link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>
        /* Center the form */
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        /* Add margin around the card with a border */
        .card {
            margin: 20px;
            border: 1px solid #ccc;
            border-radius: 8px;
            padding: 20px;
        }
        .form-label {
            display: inline-block;
            width: 150px; /* Adjust the width as needed */
            margin-right: 10px; /* Adjust the right margin as needed */
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            
            <a href="{% url 'dashboard' %}" class="btn btn-info ml-2"><i class="fas fa-arrow-left"></i> Back to Dashboard</a>
            <div class="card-body">
                <h1 class="mb-4">Schedule Train</h1>
                <form method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="id_train" class="form-label">Train:</label>
                            {{ form.train }}
                        </div>
                        <div class="form-group">
                            <label for="id_schedule_date" class="form-label">Schedule Date:</label>
                            {{ form.schedule_date }}
                        </div>
                        <div class="form-group">
                            <label for="id_departure_time" class="form-label">Departure Time:</label>
                            {{ form.departure_time }}
                        </div>
                        <div class="form-group">
                            <label for="id_destination" class="form-label">Route:</label>
                            {{ form.start_location }}
                        </div> 
                        <div class="form-group">
                            <label for="id_destination" class="form-label">Route:</label>
                            {{ form.destination }}
                        </div> 
                    <div class="btn-container">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-secondary ml-2" onclick="clearForm()">Clear</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Bootstrap JS scripts (optional) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        function clearForm() {
            document.querySelectorAll('input[type=text], input[type=date], select').forEach(input => input.value = '');
        }
    </script>
</body>
</html>

railway_booking_system/templates/train_schedule_service/train_add_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Train</title>
    <!-- Bootstrap CSS link -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <!-- Font Awesome CSS link -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <style>
        /* Center the form */
        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        /* Add space between label and input fields */
        .form-group label {
            display: inline-block;
            width: 120px; /* Adjust as needed */
            margin-right: 10px;
        }
        /* Adjust input field width */
        .form-control {
            width: 500px; /* Adjust as needed */
        }
        /* Center the buttons */
        .btn-container {
            text-align: center;
            margin-top: 20px;
        }
        /* Add margin around the card with a border */
        .card {
            margin: 20px;
            border: 1px solid #ccc;
            border-radius: 8px;
            padding: 20px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="card">
            
            <a href="{% url 'dashboard' %}" class="btn btn-info ml-2"><i class="fas fa-arrow-left"></i> Back to Dashboard</a>
            <div class="card-body">
                <h1 class="mb-4">Add Train</h1>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="id_train_name">Train Name:</label>
                        {{ form.train_name }}
                    </div>
                    <div class="form-group">
                        <label for="id_train_name">Train Route:</label>
                        {{ form.route }}
                    </div>
                    <div class="btn-container">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-secondary ml-2" onclick="clearForm()">Clear</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Bootstrap JS scripts (optional) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script>
        function clearForm() {
            document.getElementById("id_train_name").value = "";
            document.getElementById("id_train_tag").value = "";
        }
    </script>
</body>
</html>

railway_booking_system/templates/train_schedule_service/train_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Confirmation Deletion</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container mt-5">
        <div class="card">
            <div class="card-body">
                <h2 class="card-title">Confirm Deletion</h2>
                <p>Are you sure you want to delete "{{ train.train_name }}"?</p>
                <form method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>

    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>